import type { AuditLogEntry } from "../../../../infrastructure/audit/audit-log.service";

export interface IAuditLog {
  log(entry: AuditLogEntry): Promise<void>;
  logFailedLoginAttempt(params: {
    identifier: string;
    reason: string;
    ipAddress?: string;
    userAgent?: string;
    userId?: string;
  }): Promise<void>;
  logUserLogin(params: {
    userId: string;
    sessionId: string;
    ipAddress?: string;
    userAgent?: string;
    success: boolean;
    errorMessage?: string;
  }): Promise<void>;
  logUserLogout(params: {
    userId: string;
    sessionId: string;
    ipAddress?: string;
  }): Promise<void>;
  logPasswordChange(params: {
    userId: string;
    ipAddress?: string;
    userAgent?: string;
    method: "reset" | "change";
  }): Promise<void>;
  logPasswordResetRequest(params: {
    userId: string;
    ipAddress?: string;
    userAgent?: string;
  }): Promise<void>;
  logRevokeInvite(params: {
    revokedByUserId: string;
    inviteId: string;
    email?: string;
    phoneNumber?: string;
  }): Promise<void>;
  logInviteUser(params: {
    invitedByUserId: string;
    inviteId: string;
    email?: string;
    phoneNumber?: string;
    roleId: string;
  }): Promise<void>;
  logResendInvite(params: {
    resentByUserId: string;
    inviteId: string;
    email?: string;
    phoneNumber?: string;
    resendCount: number;
  }): Promise<void>;
  logAcceptInvite(params: {
    userId: string;
    inviteId: string;
    username: string;
  }): Promise<void>;
  logUserRegister(params: {
    userId: string;
    username: string;
    email: string;
  }): Promise<void>;
  logUserStatusChange(params: {
    userId: string;
    targetUserId: string;
    oldStatus: string;
    newStatus: string;
    reason?: string;
  }): Promise<void>;
  logRoleChange(params: {
    userId: string;
    targetUserId: string;
    oldRoleId: string;
    newRoleId: string;
  }): Promise<void>;
  logSessionRevoke(params: {
    userId: string;
    sessionId: string;
    revokedByUserId: string;
    reason?: string;
  }): Promise<void>;
  logSuspiciousActivity(params: {
    userId?: string;
    sessionId?: string;
    reason: string;
    ipAddress?: string;
    userAgent?: string;
    details?: Record<string, unknown>;
  }): Promise<void>;
  logEmailVerification(params: {
    userId: string;
    email: string;
  }): Promise<void>;
  logPhoneVerification(params: {
    userId: string;
    phoneNumber: string;
  }): Promise<void>;
  log2FAEnable(params: { userId: string; ipAddress?: string }): Promise<void>;
  log2FADisable(params: { userId: string; ipAddress?: string }): Promise<void>;
  logSessionCreate(params: {
    userId: string;
    sessionId: string;
    ipAddress?: string;
    userAgent?: string;
  }): Promise<void>;
  log2FARequired(params: {
    userId: string;
    ipAddress?: string;
    userAgent?: string;
  }): Promise<void>;
}
