import { relations, sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  smallint,
  text,
  time,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { businessVerticals } from "./business-verticals";
import { calendar, interactionModalityEnum, interactions } from "./calendar";
import { facilityVerticalProfiles } from "./facilities";
import { users } from "./users";
import { geometryPoint } from "../../types/geometry";

/**
 * Roteiro do dia — spec 0016.
 *
 * A roteiro is a *plan*: an ordered, time-estimated set of clinics for one
 * agent on one day, generated by the engine and edited by the agent before it
 * becomes real calendar entries. Nothing here is authoritative about what
 * happened — `interactions` and `visits` own that. This is what we intended.
 *
 * Keeping the plan is what makes the feature improvable. A slate that vanished
 * on regeneration could not tell us which suggestions reps throw away, and the
 * §4.2 weights are guesses until it can.
 */

export const roteiroStatusEnum = pgEnum("roteiro_status", [
  "DRAFT",
  "CONFIRMED",
  "DISCARDED",
  "SUPERSEDED",
]);

/**
 * Which commercial job a stop does (spec 0016 §4.3). Buckets carry quotas, so
 * that a merit ranking — which is a greedy machine — cannot spend every slate
 * on the same profitable clinics.
 */
export const roteiroBucketEnum = pgEnum("roteiro_bucket", [
  "MANTER",
  "RECUPERAR",
  "PROSPECTAR",
]);

/**
 * How the reachable set was bounded (spec 0016 §4.1).
 *
 * `LIVRE` — a circle around the rep: *what should I do today?*
 * `ANCORA` — an ellipse with the rep and an already-agreed visit as its foci:
 *   *I'm going to clinic X anyway, what else is on the way?* One expression
 *   covers both "along the route" and "around the destination", because the
 *   region near either focus is already inside the ellipse.
 *
 * Both start from live GPS. There is deliberately no stored-base or centroid
 * fallback: a centroid of scattered geometry lands in empty space, and for two
 * of five reps it puts the origin in the middle of the Amazon with nothing
 * inside 250 km (§4.1).
 */
export const roteiroReachModeEnum = pgEnum("roteiro_reach_mode", ["LIVRE", "ANCORA"]);

/**
 * `ESTIMATED` means Mapbox was unavailable and the times are straight-line
 * haversine × a road factor. It is on the row rather than inferred, because
 * every duration shown to a rep has to be labelled as one or the other.
 *
 * P1 writes `ESTIMATED` for every roteiro — the Matrix integration is P2.
 */
export const roteiroTravelSourceEnum = pgEnum("roteiro_travel_source", [
  "MAPBOX",
  "ESTIMATED",
]);

export const roteiroStopSourceEnum = pgEnum("roteiro_stop_source", [
  "SUGGESTED",
  "SUBSTITUTED",
  "MANUAL",
  "ANCHOR",
]);

export const roteiroModalitySourceEnum = pgEnum("roteiro_modality_source", [
  "SUGGESTED",
  "REP_OVERRIDE",
]);

/**
 * Why a rep threw a suggestion away. Nullable everywhere it appears — asking is
 * never allowed to block the swap, because a rep who cannot rearrange their own
 * day without filling a form stops using the feature.
 *
 * `FECHADA` raises a Não Conformidade (§9): a clinic the engine keeps proposing
 * that no longer exists is a data defect with a repair path already built.
 */
export const roteiroRejectionReasonEnum = pgEnum("roteiro_rejection_reason", [
  "MUITO_LONGE",
  "JA_VISITEI",
  "NAO_E_MEU_CLIENTE",
  "FECHADA",
  "SEM_INTERESSE",
  "OUTRO",
]);

export const roteiros = pgTable(
  "roteiros",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    /** The agent this roteiro plans a day for. */
    userId: bigint("user_id", { mode: "number" })
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    /**
     * Who generated it. Differs from `user_id` when a manager drafts a plan for
     * their rep — which they may do, while confirming it stays the rep's alone
     * (§7.3). Manager proposes, rep accepts.
     */
    createdByUserId: bigint("created_by_user_id", { mode: "number" })
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    /**
     * One roteiro per linha, never mixed (§15.1). Merit percentiles are
     * computed within the vertical, so headroom and account value — both per
     * `facility_vertical_profile` — compare like with like.
     */
    verticalId: bigint("vertical_id", { mode: "number" })
      .notNull()
      .references(() => businessVerticals.id, { onDelete: "restrict" }),
    /** The day planned, in the rep's local calendar, not UTC. */
    scopeDate: date("scope_date").notNull(),
    /**
     * Reserved for the deferred weekly mode (§4.6). Nothing writes it in v1.
     *
     * Carried now rather than added later: this table will hold confirmed
     * roteiros wired to real calendar rows long before weekly ships, and a
     * nullable column costs nothing today.
     */
    weekGroupId: uuid("week_group_id"),
    /** The rep's live GPS position when the roteiro was generated. */
    origin: geometryPoint("origin").notNull(),
    reachMode: roteiroReachModeEnum("reach_mode").notNull(),
    /**
     * The already-agreed visit that anchors the ellipse, in `ANCORA` mode. Its
     * stop carries `source = 'ANCHOR'` and the engine never moves it.
     */
    anchorProfileId: bigint("anchor_profile_id", { mode: "number" }),
    /**
     * The bound the filter actually had to use, after any step expansion —
     * a radius in `LIVRE`, a detour budget in `ANCORA`, kilometres either way.
     *
     * Stored because it is reported to the rep: "your nearest suggestion is
     * 90 km away" is a fact about their day, and a slate that quietly widened
     * its search looks identical to one that did not.
     */
    reachBoundKm: integer("reach_bound_km").notNull(),
    status: roteiroStatusEnum("status").notNull().default("DRAFT"),
    travelSource: roteiroTravelSourceEnum("travel_source").notNull(),
    /**
     * The parameters this roteiro was built from (§5.1).
     *
     * Not redundant with `roteiro_params`: weights and quotas change, and a
     * stored score must stay explainable after they do. A rep asking why
     * something was suggested last Tuesday gets last Tuesday's answer.
     */
    paramsSnapshot: jsonb("params_snapshot").$type<Record<string, unknown>>().notNull(),
    /**
     * Quotas unfilled, candidates dropped, radius expansions — everything the
     * generation could not do. Rendered on screen, never swallowed: a slate
     * missing its prospecting slot must not look like one where prospecting was
     * impossible.
     */
    notices: jsonb("notices").$type<unknown[]>().notNull().default([]),
    generatedAt: timestamp("generated_at", { withTimezone: true }).notNull().defaultNow(),
    confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
    discardedAt: timestamp("discarded_at", { withTimezone: true }),
    discardReason: text("discard_reason"),
    version: integer("version").notNull().default(1),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    /**
     * One live plan per agent per day. Regenerating supersedes the previous
     * DRAFT rather than accumulating orphans, and a CONFIRMED roteiro blocks a
     * second one — the rep's calendar has already been written.
     */
    uniqueIndex("roteiros_user_id_scope_date_live_uidx")
      .on(t.userId, t.scopeDate)
      .where(sql`status in ('DRAFT', 'CONFIRMED')`),
    index("roteiros_user_id_scope_date_idx").on(t.userId, t.scopeDate),
    index("roteiros_status_scope_date_idx").on(t.status, t.scopeDate),
    index("roteiros_vertical_id_scope_date_idx").on(t.verticalId, t.scopeDate),
    foreignKey({
      name: "roteiros_anchor_profile_id_fk",
      columns: [t.anchorProfileId],
      foreignColumns: [facilityVerticalProfiles.id],
    }).onDelete("restrict"),
    check("roteiros_reach_bound_km_positive_check", sql`${t.reachBoundKm} > 0`),
    /** An anchor is what makes the mode ÂNCORA; neither exists without the other. */
    check(
      "roteiros_anchor_matches_reach_mode_check",
      sql`(${t.reachMode} = 'ANCORA') = (${t.anchorProfileId} is not null)`,
    ),
    /**
     * A confirmed roteiro carries the instant it was confirmed — but a roteiro
     * that *was* confirmed and has since been replaced still carries it too.
     *
     * This was an equality, which read as "only a CONFIRMED row may have a
     * confirmed_at" and made SUPERSEDED unreachable from CONFIRMED: replanning
     * a day the rep had already saved failed the check and returned a 500. An
     * implication keeps the half that matters — CONFIRMED always knows when —
     * and lets the row keep its own history when the plan moves on.
     */
    check(
      "roteiros_confirmed_metadata_check",
      sql`${t.status} <> 'CONFIRMED' or ${t.confirmedAt} is not null`,
    ),
    check(
      "roteiros_discarded_metadata_check",
      sql`(${t.status} = 'DISCARDED') = (${t.discardedAt} is not null)`,
    ),
  ],
);

export const roteiroStops = pgTable(
  "roteiro_stops",
  {
    roteiroId: bigint("roteiro_id", { mode: "number" })
      .notNull()
      .references(() => roteiros.id, { onDelete: "cascade" }),
    /** 0-based and contiguous — the visiting order the rep is shown. */
    position: smallint("position").notNull(),
    /**
     * FK named explicitly below. Drizzle's derived name is 74 characters and
     * Postgres stores it truncated at 63 — the trap `facilities.ts` documents,
     * which has already cost this schema two constraints whose real names no
     * later DROP can find. `bun run db:migrate` prints the truncation as a
     * NOTICE and applies anyway, so nothing fails until someone tries to change
     * the constraint.
     */
    facilityVerticalProfileId: bigint("facility_vertical_profile_id", { mode: "number" }).notNull(),
    bucket: roteiroBucketEnum("bucket").notNull(),
    /**
     * Reuses `interaction_modality` rather than defining a parallel enum: the
     * stop becomes an interaction on confirm, and two enums meaning the same
     * thing would eventually disagree.
     *
     * Always `IN_PERSON` as generated. The column exists because a rep may flip
     * a stop to a call in the workspace (P3) and because a stop becomes a real
     * interaction, which has a modality either way — not because the engine
     * chooses one.
     */
    modality: interactionModalityEnum("modality").notNull(),
    modalitySource: roteiroModalitySourceEnum("modality_source").notNull().default("SUGGESTED"),
    meritScore: numeric("merit_score", { precision: 6, scale: 5 }).notNull(),
    /**
     * Every component's raw and weighted contribution (§5.2).
     *
     * This is what the stop card renders. **No reason shown to a rep may exist
     * that is not in here**, and none may be produced by a language model
     * (§12) — if we cannot say why, we do not suggest.
     */
    scoreBreakdown: jsonb("score_breakdown").$type<Record<string, unknown>>().notNull(),
    /** Null at position 0, and always null for REMOTE — nobody drives to a call. */
    travelSecondsFromPrev: integer("travel_seconds_from_prev"),
    serviceMinutes: smallint("service_minutes").notNull(),
    plannedStartsAt: timestamp("planned_starts_at", { withTimezone: true }).notNull(),
    plannedEndsAt: timestamp("planned_ends_at", { withTimezone: true }).notNull(),
    source: roteiroStopSourceEnum("source").notNull().default("SUGGESTED"),
    /**
     * Whether this stop filled the reserved coverage slot (§4.3.1). Stored
     * rather than re-derived: the horizon it was judged against can change, and
     * the cobertura metric must not move retroactively.
     */
    isCoverageSlot: boolean("is_coverage_slot").notNull().default(false),
    /** Written on confirm (§7.3). Null while the roteiro is a DRAFT. */
    calendarId: bigint("calendar_id", { mode: "number" }).references(() => calendar.id, {
      onDelete: "restrict",
    }),
    interactionId: bigint("interaction_id", { mode: "number" }).references(
      () => interactions.id,
      { onDelete: "restrict" },
    ),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    primaryKey({ name: "roteiro_stops_pkey", columns: [t.roteiroId, t.position] }),
    foreignKey({
      name: "roteiro_stops_profile_id_fk",
      columns: [t.facilityVerticalProfileId],
      foreignColumns: [facilityVerticalProfiles.id],
    }).onDelete("restrict"),
    /** A clinic cannot appear twice in one day's plan. */
    unique("roteiro_stops_roteiro_id_profile_id_key").on(t.roteiroId, t.facilityVerticalProfileId),
    index("roteiro_stops_profile_id_idx").on(t.facilityVerticalProfileId),
    index("roteiro_stops_interaction_id_idx").on(t.interactionId),
    check("roteiro_stops_position_non_negative_check", sql`${t.position} >= 0`),
    check("roteiro_stops_service_minutes_positive_check", sql`${t.serviceMinutes} > 0`),
    check(
      "roteiro_stops_travel_seconds_non_negative_check",
      sql`${t.travelSecondsFromPrev} is null or ${t.travelSecondsFromPrev} >= 0`,
    ),
    check("roteiro_stops_planned_window_check", sql`${t.plannedEndsAt} > ${t.plannedStartsAt}`),
    check(
      "roteiro_stops_merit_score_range_check",
      sql`${t.meritScore} >= 0 and ${t.meritScore} <= 1`,
    ),
    /**
     * A REMOTE stop has no drive. Enforced here rather than trusted to the
     * engine, because it is the invariant the whole modality feature rests on:
     * turning a 90-minute round trip into a 15-minute call is only a saving if
     * the travel really is zero.
     */
    check(
      "roteiro_stops_remote_has_no_travel_check",
      sql`${t.modality} <> 'REMOTE' or ${t.travelSecondsFromPrev} is null`,
    ),
    /** Both calendar links are written together on confirm, or neither is. */
    check(
      "roteiro_stops_confirmation_link_check",
      sql`(${t.calendarId} is null) = (${t.interactionId} is null)`,
    ),
  ],
);

/**
 * What a rep threw away, and what replaced it (§4.7).
 *
 * The most valuable table in this spec and the least obvious. A rep rejecting
 * half their slate as `NAO_E_MEU_CLIENTE` is an assignment-data problem, not a
 * preference; `FECHADA` is a clinic that should never be suggested again. None
 * of that is recoverable retroactively, so it is written from the first
 * substitution even though the manager surface that reads it is P5.
 */
export const roteiroStopRejections = pgTable(
  "roteiro_stop_rejections",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    /**
     * Null when the rejection happened in a draft.
     *
     * A rep works the slate before it is a roteiro — generate, drop one, look
     * again — and a preview is deliberately never persisted (§7.3). Requiring a
     * roteiro would therefore throw away every rejection made at the only moment
     * a rep actually makes them.
     */
    roteiroId: bigint("roteiro_id", { mode: "number" }).references(() => roteiros.id, {
      onDelete: "cascade",
    }),
    /**
     * Whose rejection. Carried on the row rather than reached through
     * `roteiros` because it is what scoring keys on — one rep's "not my client"
     * is another rep's account — and because a draft rejection has no roteiro
     * to reach through.
     */
    userId: bigint("user_id", { mode: "number" })
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    verticalId: bigint("vertical_id", { mode: "number" })
      .notNull()
      .references(() => businessVerticals.id, { onDelete: "restrict" }),
    position: smallint("position"),
    /** Both profile FKs are named explicitly below — see `roteiro_stops`. */
    rejectedProfileId: bigint("rejected_profile_id", { mode: "number" }).notNull(),
    /** Null when the rep removed the stop instead of swapping it. */
    replacedByProfileId: bigint("replaced_by_profile_id", { mode: "number" }),
    reason: roteiroRejectionReasonEnum("reason"),
    reasonNote: text("reason_note"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    foreignKey({
      name: "roteiro_stop_rejections_rejected_profile_id_fk",
      columns: [t.rejectedProfileId],
      foreignColumns: [facilityVerticalProfiles.id],
    }).onDelete("restrict"),
    foreignKey({
      name: "roteiro_stop_rejections_replaced_profile_id_fk",
      columns: [t.replacedByProfileId],
      foreignColumns: [facilityVerticalProfiles.id],
    }).onDelete("restrict"),
    index("roteiro_stop_rejections_roteiro_id_idx").on(t.roteiroId),
    index("roteiro_stop_rejections_rejected_profile_id_idx").on(t.rejectedProfileId),
    // How generation reads it: every rejection this rep has made about this
    // clinic, newest first, to decay and sum (§15.5.2).
    index("roteiro_stop_rejections_user_profile_idx").on(
      t.userId,
      t.rejectedProfileId,
      t.createdAt,
    ),
    index("roteiro_stop_rejections_reason_created_at_idx").on(t.reason, t.createdAt),
  ],
);

/**
 * How the engine thinks, per linha — spec 0016 §6.3.
 *
 * Every tunable lives here rather than in code, because all of them are
 * commercial judgements that will be wrong before the next deploy. The measured
 * defaults (§4.9) are a starting point calibrated against a book that is 93.8 %
 * prospects; they will be wrong again once the funnel fills, and that is the
 * point of the table.
 */
export const roteiroParams = pgTable(
  "roteiro_params",
  {
    verticalId: bigint("vertical_id", { mode: "number" })
      .primaryKey()
      .references(() => businessVerticals.id, { onDelete: "cascade" }),
    /** The hard ceiling. A request may ask for fewer, never more (§6.2). */
    dailyLimit: smallint("daily_limit").notNull().default(5),
    /** `{ t, h, n, v, k, c, q }` — must sum to 1 (§4.2). */
    weights: jsonb("weights").$type<Record<string, number>>().notNull(),
    /** `{ MANTER, RECUPERAR, PROSPECTAR }` slot ratios (§4.3). */
    bucketRatios: jsonb("bucket_ratios").$type<Record<string, number>>().notNull(),
    /** Days since the last COMPLETED interaction before a clinic is offered again. */
    cooldownDays: jsonb("cooldown_days").$type<Record<string, number>>().notNull(),
    /** Days before a clinic is overdue for coverage (§4.3.1), per bucket. */
    coverageHorizonDays: jsonb("coverage_horizon_days").$type<Record<string, number>>().notNull(),
    /** Visit duration by modality, with optional per-bucket overrides. */
    serviceMinutes: jsonb("service_minutes").$type<Record<string, unknown>>().notNull(),
    /**
     * Per CNES unit type: `fit` (where it ranks), `eligible` (whether it may be
     * proposed at all, and whether it counts toward cobertura) and
     * `forceRemote` (§4.2g). `"*"` is the fallback, which is what catches
     * staffing cooperatives without enumerating every administrative type.
     *
     * ⚠️ Keys are `registry.unit_types.name` — CNES's strings, not ours. A
     * reload that renames one silently drops it to `"*"`, so the params editor
     * offers the catalogue as a picker and an unmatched key is reported.
     */
    unitTypePolicy: jsonb("unit_type_policy").$type<Record<string, unknown>>().notNull(),
    /** `LIVRE` mode: circle radius around the rep, expanded stepwise when sparse (§4.1). */
    reachRadiusKm: integer("reach_radius_km").notNull().default(60),
    /**
     * `ANCORA` mode: how far off the direct route a clinic may sit and still
     * count as "on the way". Measured on rep 3's book against a 5.5 km anchor
     * drive — 5 km admits 22 candidates, 20 km → 81, 40 km → 139.
     */
    detourBudgetKm: integer("detour_budget_km").notNull().default(20),
    /** Detour tolerance in the `gain` denominator (§4.5). Higher = travel further for quality. */
    tauSeconds: integer("tau_seconds").notNull().default(900),
    /** Beyond this drive, a mid-merit clinic is proposed as a call (§4.4). */
    remoteThresholdSeconds: integer("remote_threshold_seconds").notNull().default(2700),
    /**
     * What an unsurveyed clinic's headroom scores. Deliberately mid-band, never
     * 0: scoring the unknown as worthless guarantees the engine never sends a
     * rep to the clinics it knows least about, which is exactly backwards.
     */
    headroomUnknown: numeric("headroom_unknown", { precision: 4, scale: 3 })
      .notNull()
      .default("0.400"),
    /**
     * What capacity scores when CNES has no staff row for the facility at all.
     *
     * Absent is not zero. 15% of the book has no row, and a registry load that
     * half-fails does not announce itself — it just makes clinics look
     * worthless. CNES may only ever raise confidence in a clinic, never lower
     * it: its absence means we have not looked, and not having looked is a
     * reason to visit.
     */
    capacityUnknown: numeric("capacity_unknown", { precision: 4, scale: 3 })
      .notNull()
      .default("0.400"),
    workdayStart: time("workday_start").notNull().default("08:00"),
    workdayEnd: time("workday_end").notNull().default("18:00"),
    maxGenerationsPerDay: smallint("max_generations_per_day").notNull().default(20),
    updatedByUserId: bigint("updated_by_user_id", { mode: "number" }).references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    check(
      "roteiro_params_daily_limit_range_check",
      sql`${t.dailyLimit} between 1 and 12`,
    ),
    check("roteiro_params_reach_radius_km_positive_check", sql`${t.reachRadiusKm} > 0`),
    check("roteiro_params_detour_budget_km_positive_check", sql`${t.detourBudgetKm} > 0`),
    check("roteiro_params_tau_seconds_positive_check", sql`${t.tauSeconds} > 0`),
    check(
      "roteiro_params_remote_threshold_positive_check",
      sql`${t.remoteThresholdSeconds} > 0`,
    ),
    check(
      "roteiro_params_headroom_unknown_range_check",
      sql`${t.headroomUnknown} >= 0 and ${t.headroomUnknown} <= 1`,
    ),
    check(
      "roteiro_params_capacity_unknown_range_check",
      sql`${t.capacityUnknown} >= 0 and ${t.capacityUnknown} <= 1`,
    ),
    check("roteiro_params_workday_order_check", sql`${t.workdayEnd} > ${t.workdayStart}`),
    check(
      "roteiro_params_max_generations_positive_check",
      sql`${t.maxGenerationsPerDay} > 0`,
    ),
    /**
     * The weights must sum to 1, checked in the database.
     *
     * Application discipline is not enough here: a weight vector summing to 1.4
     * still produces a plausible ranking, so nothing fails and every stored
     * `merit_score` is quietly on a different scale from every other roteiro's.
     * Rounded to 4 decimals because these are hand-entered decimals.
     */
    check(
      "roteiro_params_weights_sum_to_one_check",
      sql`round((
        (${t.weights}->>'t')::numeric + (${t.weights}->>'h')::numeric +
        (${t.weights}->>'n')::numeric + (${t.weights}->>'v')::numeric +
        (${t.weights}->>'k')::numeric + (${t.weights}->>'c')::numeric +
        (${t.weights}->>'q')::numeric), 4) = 1.0000`,
    ),
  ],
);

export const roteirosRelations = relations(roteiros, ({ one, many }) => ({
  user: one(users, {
    fields: [roteiros.userId],
    references: [users.id],
    relationName: "roteiroAgent",
  }),
  createdBy: one(users, {
    fields: [roteiros.createdByUserId],
    references: [users.id],
    relationName: "roteiroCreatedBy",
  }),
  vertical: one(businessVerticals, {
    fields: [roteiros.verticalId],
    references: [businessVerticals.id],
  }),
  stops: many(roteiroStops),
  rejections: many(roteiroStopRejections),
}));

export const roteiroStopsRelations = relations(roteiroStops, ({ one }) => ({
  roteiro: one(roteiros, {
    fields: [roteiroStops.roteiroId],
    references: [roteiros.id],
  }),
  verticalProfile: one(facilityVerticalProfiles, {
    fields: [roteiroStops.facilityVerticalProfileId],
    references: [facilityVerticalProfiles.id],
  }),
  calendarEvent: one(calendar, {
    fields: [roteiroStops.calendarId],
    references: [calendar.id],
  }),
  interaction: one(interactions, {
    fields: [roteiroStops.interactionId],
    references: [interactions.id],
  }),
}));

export const roteiroStopRejectionsRelations = relations(roteiroStopRejections, ({ one }) => ({
  roteiro: one(roteiros, {
    fields: [roteiroStopRejections.roteiroId],
    references: [roteiros.id],
  }),
  rejectedProfile: one(facilityVerticalProfiles, {
    fields: [roteiroStopRejections.rejectedProfileId],
    references: [facilityVerticalProfiles.id],
    relationName: "roteiroRejectedProfile",
  }),
  replacedByProfile: one(facilityVerticalProfiles, {
    fields: [roteiroStopRejections.replacedByProfileId],
    references: [facilityVerticalProfiles.id],
    relationName: "roteiroReplacementProfile",
  }),
}));

export const roteiroParamsRelations = relations(roteiroParams, ({ one }) => ({
  vertical: one(businessVerticals, {
    fields: [roteiroParams.verticalId],
    references: [businessVerticals.id],
  }),
}));
