export {
  canManageUsers,
  canReadClinics,
  canManageClinics,
  canReadDoctors,
  canManageDoctors,
  canReadTerritories,
  canManageTerritories,
  canCreateTerritories,
  canUpdateTerritories,
  canViewHealth,
  hasMinimumRole,
  hasMinimumRole as hasRole,
  isAdmin,
} from "@atlasmed/access";
