export {
  canManageUsers,
  canReadFacilities,
  canManageFacilities,
  canReadProfessionals,
  canManageProfessionals,
  canReadTerritories,
  canManageTerritories,
  canCreateTerritories,
  canUpdateTerritories,
  canViewHealth,
  hasMinimumRole,
  hasMinimumRole as hasRole,
  isAdmin,
} from "@atlasmed/access";
