export const Subjects = {
  USER: "USER",

  FACILITY: "FACILITY",

  PROFESSIONAL: "PROFESSIONAL",

  VISIT: "VISIT",

  TERRITORY: "TERRITORY",

  INVITATION: "INVITATION",

  REGISTRY_INGESTION: "REGISTRY_INGESTION",

  REGISTRY_SUGGESTION: "REGISTRY_SUGGESTION",

  CATALOG: "CATALOG",
} as const;

export type Subject = (typeof Subjects)[keyof typeof Subjects];
